name: CI-macOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macOS:
    runs-on: macos-15
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test
        run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES

  build-and-test-iOS:
    runs-on: macos-15
    timeout-minutes: 8

    steps:
      - name: Show available simulators
        run: xcrun simctl list devices

      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Boot simulator
        run: |
        xcrun simctl boot "0E573B10-C4F3-40D6-A8CB-08B18F25CE08" || true
        xcrun simctl bootstatus "0E573B10-C4F3-40D6-A8CB-08B18F25CE08" -b

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test
        run: xcodebuild clean build test -workspace EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination 'platform=iOS Simulator,id=0E573B10-C4F3-40D6-A8CB-08B18F25CE08'


