name: CI-macOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macOS:
    runs-on: macos-15
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test (macOS)
        run: |
          xcodebuild clean build test \
            -project EssentialFeed/EssentialFeed.xcodeproj \
            -scheme "CI" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -destination "platform=macOS" \
            ONLY_ACTIVE_ARCH=YES

  build-and-test-iOS:
    runs-on: macos-15-xlarge
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Check and use available iOS version
        run: |
          echo "Available iOS simulators:"
          xcrun simctl list devices | grep -E "(iOS|iPhone)"
          echo "Using available iOS version instead of downloading"

      - name: Boot iOS Simulator
        run: |
          # Boot the specific simulator
          xcrun simctl boot "9F13B89D-34C6-45A5-9209-6DAC3E11D89B"
          # Wait for it to be ready
          sleep 10
          # Verify it's booted
          xcrun simctl list devices | grep Booted
        
      - name: Test with EssentialApp scheme instead
        run: |
          xcodebuild clean build test \
            -workspace EssentialApp.xcworkspace \
            -scheme "EssentialApp" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4" ONLY_ACTIVE_ARCH=YES

      - name: Build and Test (iOS)
        run: |
          xcodebuild clean build test \
            -workspace EssentialApp.xcworkspace \
            -scheme "CI_iOS" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
             -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4" ONLY_ACTIVE_ARCH=YES
